//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SharpCircuit.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SharpCircuit.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap ASSIGNMENT_DECK_1 {
            get {
                object obj = ResourceManager.GetObject("ASSIGNMENT_DECK_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap ASSIGNMENT_DECK_2 {
            get {
                object obj = ResourceManager.GetObject("ASSIGNMENT_DECK_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap ASSIGNMENT_DECK_3 {
            get {
                object obj = ResourceManager.GetObject("ASSIGNMENT_DECK_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap ASSIGNMENT_DECK_4 {
            get {
                object obj = ResourceManager.GetObject("ASSIGNMENT_DECK_4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap BLOWER_ANIM {
            get {
                object obj = ResourceManager.GetObject("BLOWER_ANIM", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap BLOWER_ANIM_STOPPED {
            get {
                object obj = ResourceManager.GetObject("BLOWER_ANIM_STOPPED", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap BLOWER_CONTACTOR {
            get {
                object obj = ResourceManager.GetObject("BLOWER_CONTACTOR", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap BLOWER_CONTACTOR_CLOSED {
            get {
                object obj = ResourceManager.GetObject("BLOWER_CONTACTOR_CLOSED", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap BLOWER_CONTACTOR_OPEN {
            get {
                object obj = ResourceManager.GetObject("BLOWER_CONTACTOR_OPEN", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap BLOWER_CONTACTOR_RESET_DOWN {
            get {
                object obj = ResourceManager.GetObject("BLOWER_CONTACTOR_RESET_DOWN", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap BLOWER_CONTACTOR_RESET_UP {
            get {
                object obj = ResourceManager.GetObject("BLOWER_CONTACTOR_RESET_UP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap BLOWER_CONTACTOR_TRIP_DOWN {
            get {
                object obj = ResourceManager.GetObject("BLOWER_CONTACTOR_TRIP_DOWN", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap BLOWER_CONTACTOR_TRIP_UP {
            get {
                object obj = ResourceManager.GetObject("BLOWER_CONTACTOR_TRIP_UP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;CAN&quot;,&quot;AC11&quot;,&quot;1&quot;,&quot;1&quot;,&quot;V-11&quot;,&quot;0&quot;,&quot;INPUT&quot;,&quot;801&quot;,&quot;01&quot;,
        ///&quot;CAN&quot;,&quot;AC115&quot;,&quot;115&quot;,&quot;6&quot;,&quot;VAC-115&quot;,&quot;115&quot;,&quot;115V&quot;,&quot;801&quot;,&quot;01&quot;,
        ///&quot;CAN&quot;,&quot;AC12&quot;,&quot;1&quot;,&quot;28&quot;,&quot;V-12&quot;,&quot;0&quot;,&quot;INPUT&quot;,&quot;801&quot;,&quot;01&quot;,
        ///&quot;CAN&quot;,&quot;AC13&quot;,&quot;1&quot;,&quot;2&quot;,&quot;V-13&quot;,&quot;0&quot;,&quot;INPUT&quot;,&quot;801&quot;,&quot;01&quot;,
        ///&quot;CAN&quot;,&quot;AC14&quot;,&quot;1&quot;,&quot;29&quot;,&quot;V-14&quot;,&quot;0&quot;,&quot;INPUT&quot;,&quot;801&quot;,&quot;01&quot;,
        ///&quot;CAN&quot;,&quot;AC15&quot;,&quot;1&quot;,&quot;3&quot;,&quot;V-15&quot;,&quot;0&quot;,&quot;INPUT&quot;,&quot;801&quot;,&quot;01&quot;,
        ///&quot;CAN&quot;,&quot;AC16&quot;,&quot;1&quot;,&quot;30&quot;,&quot;V-16&quot;,&quot;0&quot;,&quot;INPUT&quot;,&quot;801&quot;,&quot;01&quot;,
        ///&quot;CAN&....
        /// </summary>
        public static string CANCON_1 {
            get {
                return ResourceManager.GetString("CANCON_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap CB_BUTTON_CLOSE_DOWN {
            get {
                object obj = ResourceManager.GetObject("CB_BUTTON_CLOSE_DOWN", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap CB_BUTTON_CLOSE_UP {
            get {
                object obj = ResourceManager.GetObject("CB_BUTTON_CLOSE_UP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap CB_BUTTON_OPEN_DOWN {
            get {
                object obj = ResourceManager.GetObject("CB_BUTTON_OPEN_DOWN", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap CB_BUTTON_OPEN_UP {
            get {
                object obj = ResourceManager.GetObject("CB_BUTTON_OPEN_UP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap CB_CONTROL {
            get {
                object obj = ResourceManager.GetObject("CB_CONTROL", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap CB_INDICATION_CLOSED {
            get {
                object obj = ResourceManager.GetObject("CB_INDICATION_CLOSED", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap CB_INDICATION_OPEN {
            get {
                object obj = ResourceManager.GetObject("CB_INDICATION_OPEN", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap CONTACTOR_1250_CLOSED {
            get {
                object obj = ResourceManager.GetObject("CONTACTOR_1250_CLOSED", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap CONTACTOR_1250_OPEN {
            get {
                object obj = ResourceManager.GetObject("CONTACTOR_1250_OPEN", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap CONTACTOR_1800_CLOSED {
            get {
                object obj = ResourceManager.GetObject("CONTACTOR_1800_CLOSED", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap CONTACTOR_1800_OPEN {
            get {
                object obj = ResourceManager.GetObject("CONTACTOR_1800_OPEN", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap CONTACTOR_REVERSER_CLOSED_BOTTOM {
            get {
                object obj = ResourceManager.GetObject("CONTACTOR_REVERSER_CLOSED_BOTTOM", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap CONTACTOR_REVERSER_CLOSED_TOP {
            get {
                object obj = ResourceManager.GetObject("CONTACTOR_REVERSER_CLOSED_TOP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap CONTACTOR_REVERSER_OPEN {
            get {
                object obj = ResourceManager.GetObject("CONTACTOR_REVERSER_OPEN", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap DCMODULE {
            get {
                object obj = ResourceManager.GetObject("DCMODULE", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap DCMODULE_KNOB {
            get {
                object obj = ResourceManager.GetObject("DCMODULE_KNOB", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap DCMODULE_LED_OFF {
            get {
                object obj = ResourceManager.GetObject("DCMODULE_LED_OFF", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap DCMODULE_LED_ON {
            get {
                object obj = ResourceManager.GetObject("DCMODULE_LED_ON", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap DCMODULE_METER {
            get {
                object obj = ResourceManager.GetObject("DCMODULE_METER", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap DCMODULE_METER_BASE {
            get {
                object obj = ResourceManager.GetObject("DCMODULE_METER_BASE", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap DCMODULE_METER_OVERLAY {
            get {
                object obj = ResourceManager.GetObject("DCMODULE_METER_OVERLAY", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap DCMODULE_SWITCH_DOWN {
            get {
                object obj = ResourceManager.GetObject("DCMODULE_SWITCH_DOWN", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap DCMODULE_SWITCH_UP {
            get {
                object obj = ResourceManager.GetObject("DCMODULE_SWITCH_UP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap DECK_1_BUTTON {
            get {
                object obj = ResourceManager.GetObject("DECK_1_BUTTON", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap DECK_1_BUTTON_OVER {
            get {
                object obj = ResourceManager.GetObject("DECK_1_BUTTON_OVER", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap DECK_1_BUTTON_SELECTED {
            get {
                object obj = ResourceManager.GetObject("DECK_1_BUTTON_SELECTED", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap DECK_2_BUTTON {
            get {
                object obj = ResourceManager.GetObject("DECK_2_BUTTON", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap DECK_2_BUTTON_OVER {
            get {
                object obj = ResourceManager.GetObject("DECK_2_BUTTON_OVER", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap DECK_2_BUTTON_SELECTED {
            get {
                object obj = ResourceManager.GetObject("DECK_2_BUTTON_SELECTED", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap DECK_3_BUTTON {
            get {
                object obj = ResourceManager.GetObject("DECK_3_BUTTON", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap DECK_3_BUTTON_OVER {
            get {
                object obj = ResourceManager.GetObject("DECK_3_BUTTON_OVER", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap DECK_3_BUTTON_SELECTED {
            get {
                object obj = ResourceManager.GetObject("DECK_3_BUTTON_SELECTED", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap DECK_4_BUTTON {
            get {
                object obj = ResourceManager.GetObject("DECK_4_BUTTON", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap DECK_4_BUTTON_OVER {
            get {
                object obj = ResourceManager.GetObject("DECK_4_BUTTON_OVER", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap DECK_4_BUTTON_SELECTED {
            get {
                object obj = ResourceManager.GetObject("DECK_4_BUTTON_SELECTED", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap DrillersConsoleClosed {
            get {
                object obj = ResourceManager.GetObject("DrillersConsoleClosed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap DrillersConsoleDoor {
            get {
                object obj = ResourceManager.GetObject("DrillersConsoleDoor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap DrillersConsoleOpen {
            get {
                object obj = ResourceManager.GetObject("DrillersConsoleOpen", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] DSEG7Classic_BoldItalic {
            get {
                object obj = ResourceManager.GetObject("DSEG7Classic_BoldItalic", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap DVM {
            get {
                object obj = ResourceManager.GetObject("DVM", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap DVM_KNOB {
            get {
                object obj = ResourceManager.GetObject("DVM_KNOB", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap EM_STOP_DOWN {
            get {
                object obj = ResourceManager.GetObject("EM_STOP_DOWN", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap EM_STOP_UP {
            get {
                object obj = ResourceManager.GetObject("EM_STOP_UP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap FOOT_THROTTLE {
            get {
                object obj = ResourceManager.GetObject("FOOT_THROTTLE", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap FOOT_THROTTLE_PADDLE {
            get {
                object obj = ResourceManager.GetObject("FOOT_THROTTLE_PADDLE", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap FRONT_BUTTON {
            get {
                object obj = ResourceManager.GetObject("FRONT_BUTTON", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap FRONT_BUTTON_OVER {
            get {
                object obj = ResourceManager.GetObject("FRONT_BUTTON_OVER", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap FRONT_BUTTON_SELECTED {
            get {
                object obj = ResourceManager.GetObject("FRONT_BUTTON_SELECTED", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap HANDWHEEL_3 {
            get {
                object obj = ResourceManager.GetObject("HANDWHEEL_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap HANDWHEEL_4 {
            get {
                object obj = ResourceManager.GetObject("HANDWHEEL_4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] heavy_throw_switch {
            get {
                object obj = ResourceManager.GetObject("heavy_throw_switch", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon ICON {
            get {
                object obj = ResourceManager.GetObject("ICON", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap KNOB_1 {
            get {
                object obj = ResourceManager.GetObject("KNOB_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap LAMP_GREEN_OFF {
            get {
                object obj = ResourceManager.GetObject("LAMP_GREEN_OFF", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap LAMP_GREEN_ON {
            get {
                object obj = ResourceManager.GetObject("LAMP_GREEN_ON", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap LAMP_RED_OFF {
            get {
                object obj = ResourceManager.GetObject("LAMP_RED_OFF", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap LAMP_RED_ON {
            get {
                object obj = ResourceManager.GetObject("LAMP_RED_ON", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] large_castle_metal_door_slammed_close {
            get {
                object obj = ResourceManager.GetObject("large_castle_metal_door_slammed_close", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap MCC_BREAKER_CLOSED {
            get {
                object obj = ResourceManager.GetObject("MCC_BREAKER_CLOSED", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap MCC_BREAKER_OPEN {
            get {
                object obj = ResourceManager.GetObject("MCC_BREAKER_OPEN", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap MCC_BREAKER_TRIPPED {
            get {
                object obj = ResourceManager.GetObject("MCC_BREAKER_TRIPPED", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap MCC_CABINET {
            get {
                object obj = ResourceManager.GetObject("MCC_CABINET", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap MCC_CAN {
            get {
                object obj = ResourceManager.GetObject("MCC_CAN", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap MCC_CONTACTOR {
            get {
                object obj = ResourceManager.GetObject("MCC_CONTACTOR", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap MCC_CONTACTOR_CLOSED {
            get {
                object obj = ResourceManager.GetObject("MCC_CONTACTOR_CLOSED", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap MCC_CONTACTOR_OPEN {
            get {
                object obj = ResourceManager.GetObject("MCC_CONTACTOR_OPEN", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] metal_door_close {
            get {
                object obj = ResourceManager.GetObject("metal_door_close", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap MOTOR_BOX {
            get {
                object obj = ResourceManager.GetObject("MOTOR_BOX", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap PANEL_METER_BASE {
            get {
                object obj = ResourceManager.GetObject("PANEL_METER_BASE", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap PANEL_METER_OVERLAY {
            get {
                object obj = ResourceManager.GetObject("PANEL_METER_OVERLAY", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap PANEL_METER_POINTER {
            get {
                object obj = ResourceManager.GetObject("PANEL_METER_POINTER", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap PANEL_METER_SCALE_1000ADC {
            get {
                object obj = ResourceManager.GetObject("PANEL_METER_SCALE_1000ADC", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap PANEL_METER_SCALE_1000VDC {
            get {
                object obj = ResourceManager.GetObject("PANEL_METER_SCALE_1000VDC", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap PANEL_METER_SCALE_2000ADC {
            get {
                object obj = ResourceManager.GetObject("PANEL_METER_SCALE_2000ADC", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap PB_BLACK_DOWN {
            get {
                object obj = ResourceManager.GetObject("PB_BLACK_DOWN", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap PB_BLACK_UP {
            get {
                object obj = ResourceManager.GetObject("PB_BLACK_UP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap PB_GREEN_DOWN {
            get {
                object obj = ResourceManager.GetObject("PB_GREEN_DOWN", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap PB_GREEN_UP {
            get {
                object obj = ResourceManager.GetObject("PB_GREEN_UP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap PB_RED_DOWN {
            get {
                object obj = ResourceManager.GetObject("PB_RED_DOWN", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap PB_RED_UP {
            get {
                object obj = ResourceManager.GetObject("PB_RED_UP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] ping_switch {
            get {
                object obj = ResourceManager.GetObject("ping_switch", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap PISTOL_GRIP {
            get {
                object obj = ResourceManager.GetObject("PISTOL_GRIP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap POT_REAR_BASE {
            get {
                object obj = ResourceManager.GetObject("POT_REAR_BASE", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap POT_REAR_BODY {
            get {
                object obj = ResourceManager.GetObject("POT_REAR_BODY", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap POT_REAR_END_STOP {
            get {
                object obj = ResourceManager.GetObject("POT_REAR_END_STOP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap POT_REAR_WIPER {
            get {
                object obj = ResourceManager.GetObject("POT_REAR_WIPER", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap POT_WIRES_DW_FRONT {
            get {
                object obj = ResourceManager.GetObject("POT_WIRES_DW_FRONT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap POT_WIRES_DW_REAR {
            get {
                object obj = ResourceManager.GetObject("POT_WIRES_DW_REAR", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap POT_WIRES_MP1_FRONT {
            get {
                object obj = ResourceManager.GetObject("POT_WIRES_MP1_FRONT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap POT_WIRES_MP1_FRONT_RESOURCE {
            get {
                object obj = ResourceManager.GetObject("POT_WIRES_MP1_FRONT_RESOURCE", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap POT_WIRES_MP1_REAR {
            get {
                object obj = ResourceManager.GetObject("POT_WIRES_MP1_REAR", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap POT_WIRES_MP2_FRONT {
            get {
                object obj = ResourceManager.GetObject("POT_WIRES_MP2_FRONT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap POT_WIRES_MP2_REAR {
            get {
                object obj = ResourceManager.GetObject("POT_WIRES_MP2_REAR", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap POT_WIRES_RESOURCE {
            get {
                object obj = ResourceManager.GetObject("POT_WIRES_RESOURCE", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap POT_WIRES_RT_FRONT {
            get {
                object obj = ResourceManager.GetObject("POT_WIRES_RT_FRONT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap POT_WIRES_RT_REAR {
            get {
                object obj = ResourceManager.GetObject("POT_WIRES_RT_REAR", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] power_plant_ambience_with_constant_light_roar {
            get {
                object obj = ResourceManager.GetObject("power_plant_ambience_with_constant_light_roar", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] power_plant_ambience_with_constant_light_roar_cut {
            get {
                object obj = ResourceManager.GetObject("power_plant_ambience_with_constant_light_roar_cut", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap REAR_BUTTON {
            get {
                object obj = ResourceManager.GetObject("REAR_BUTTON", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap REAR_BUTTON_OVER {
            get {
                object obj = ResourceManager.GetObject("REAR_BUTTON_OVER", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap REAR_BUTTON_OVER1 {
            get {
                object obj = ResourceManager.GetObject("REAR_BUTTON_OVER1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap REAR_BUTTON_SELECTED {
            get {
                object obj = ResourceManager.GetObject("REAR_BUTTON_SELECTED", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap SCR_LAMP_OFF {
            get {
                object obj = ResourceManager.GetObject("SCR_LAMP_OFF", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap SCR_LAMP_ON {
            get {
                object obj = ResourceManager.GetObject("SCR_LAMP_ON", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap SCR_OUTER_FRAME {
            get {
                object obj = ResourceManager.GetObject("SCR_OUTER_FRAME", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap SCR1_AUCTIONEERING {
            get {
                object obj = ResourceManager.GetObject("SCR1_AUCTIONEERING", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap SCR1_CONTACTOR_WIRES {
            get {
                object obj = ResourceManager.GetObject("SCR1_CONTACTOR_WIRES", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap SCR1_DOOR {
            get {
                object obj = ResourceManager.GetObject("SCR1_DOOR", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap SCR1_LABEL {
            get {
                object obj = ResourceManager.GetObject("SCR1_LABEL", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap SCR1_RELAY {
            get {
                object obj = ResourceManager.GetObject("SCR1_RELAY", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap SCR1_TERMINALS {
            get {
                object obj = ResourceManager.GetObject("SCR1_TERMINALS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap SCR2_AUCTIONEERING {
            get {
                object obj = ResourceManager.GetObject("SCR2_AUCTIONEERING", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap SCR2_CONTACTOR_WIRES {
            get {
                object obj = ResourceManager.GetObject("SCR2_CONTACTOR_WIRES", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap SCR2_DOOR {
            get {
                object obj = ResourceManager.GetObject("SCR2_DOOR", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap SCR2_LABEL {
            get {
                object obj = ResourceManager.GetObject("SCR2_LABEL", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap SCR2_RELAY {
            get {
                object obj = ResourceManager.GetObject("SCR2_RELAY", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap SCR2_TERMINALS {
            get {
                object obj = ResourceManager.GetObject("SCR2_TERMINALS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap SCR2Closed {
            get {
                object obj = ResourceManager.GetObject("SCR2Closed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap SCR2Door {
            get {
                object obj = ResourceManager.GetObject("SCR2Door", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap SCR2Open {
            get {
                object obj = ResourceManager.GetObject("SCR2Open", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap SCR2Relay {
            get {
                object obj = ResourceManager.GetObject("SCR2Relay", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap SCR3_AUCTIONEERING {
            get {
                object obj = ResourceManager.GetObject("SCR3_AUCTIONEERING", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap SCR3_CONTACTOR_WIRES {
            get {
                object obj = ResourceManager.GetObject("SCR3_CONTACTOR_WIRES", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap SCR3_DOOR {
            get {
                object obj = ResourceManager.GetObject("SCR3_DOOR", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap SCR3_LABEL {
            get {
                object obj = ResourceManager.GetObject("SCR3_LABEL", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap SCR3_RELAY {
            get {
                object obj = ResourceManager.GetObject("SCR3_RELAY", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap SCR3_TERMINALS {
            get {
                object obj = ResourceManager.GetObject("SCR3_TERMINALS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap SCR4_AUCTIONEERING {
            get {
                object obj = ResourceManager.GetObject("SCR4_AUCTIONEERING", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap SCR4_CONTACTOR_WIRES {
            get {
                object obj = ResourceManager.GetObject("SCR4_CONTACTOR_WIRES", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap SCR4_DOOR {
            get {
                object obj = ResourceManager.GetObject("SCR4_DOOR", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap SCR4_LABEL {
            get {
                object obj = ResourceManager.GetObject("SCR4_LABEL", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap SCR4_RELAY {
            get {
                object obj = ResourceManager.GetObject("SCR4_RELAY", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap SCR4_TERMINALS {
            get {
                object obj = ResourceManager.GetObject("SCR4_TERMINALS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap SCRClosed {
            get {
                object obj = ResourceManager.GetObject("SCRClosed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap SCRDoor {
            get {
                object obj = ResourceManager.GetObject("SCRDoor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] SCRIPT_001 {
            get {
                object obj = ResourceManager.GetObject("SCRIPT_001", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] SCRIPT_002 {
            get {
                object obj = ResourceManager.GetObject("SCRIPT_002", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] SCRLogic {
            get {
                object obj = ResourceManager.GetObject("SCRLogic", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] SCRLogic_Drawing_Book {
            get {
                object obj = ResourceManager.GetObject("SCRLogic_Drawing_Book", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap SCROpen {
            get {
                object obj = ResourceManager.GetObject("SCROpen", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap SCRRelay {
            get {
                object obj = ResourceManager.GetObject("SCRRelay", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] siren {
            get {
                object obj = ResourceManager.GetObject("siren", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap SPLASH {
            get {
                object obj = ResourceManager.GetObject("SPLASH", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap SWITCH_1 {
            get {
                object obj = ResourceManager.GetObject("SWITCH_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] thunk_switch {
            get {
                object obj = ResourceManager.GetObject("thunk_switch", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;DC&quot;,&quot;D81&quot;,&quot;A&quot;,&quot;241&quot;,&quot;D81&quot;,&quot;0&quot;,&quot;&quot;,&quot;402&quot;,&quot;01&quot;,
        ///&quot;DC&quot;,&quot;D81&quot;,&quot;K&quot;,&quot;102&quot;,&quot;D81&quot;,&quot;0&quot;,&quot;&quot;,&quot;402&quot;,&quot;01&quot;,
        ///&quot;DC&quot;,&quot;D810&quot;,&quot;A&quot;,&quot;LTEST12P&quot;,&quot;D810&quot;,&quot;0&quot;,&quot;&quot;,&quot;402&quot;,&quot;01&quot;,
        ///&quot;DC&quot;,&quot;D810&quot;,&quot;K&quot;,&quot;226&quot;,&quot;D810&quot;,&quot;0&quot;,&quot;&quot;,&quot;402&quot;,&quot;01&quot;,
        ///&quot;DC&quot;,&quot;D811&quot;,&quot;A&quot;,&quot;LTEST12P&quot;,&quot;D811&quot;,&quot;0&quot;,&quot;&quot;,&quot;402&quot;,&quot;02&quot;,
        ///&quot;DC&quot;,&quot;D811&quot;,&quot;K&quot;,&quot;230&quot;,&quot;D811&quot;,&quot;0&quot;,&quot;&quot;,&quot;402&quot;,&quot;02&quot;,
        ///&quot;DC&quot;,&quot;D812&quot;,&quot;A&quot;,&quot;LTEST12P&quot;,&quot;D812&quot;,&quot;0&quot;,&quot;&quot;,&quot;402&quot;,&quot;02&quot;,
        ///&quot;DC&quot;,&quot;D812&quot;,&quot....
        /// </summary>
        public static string WIRECON {
            get {
                return ResourceManager.GetString("WIRECON", resourceCulture);
            }
        }
    }
}
